# This workflow is based on the npm template: https://github.com/actions/starter-workflows/blob/main/ci/node.js.yml
name: build-and-test
on:
  push:
    branches:
      - main
      - master
      - gha
  pull_request:
    branches:
      - main
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 15.x
      - run: npm run-script build
      - run: npm install codecov -g
      - run: npm run-script test
      - run: npm run-script lint
      - uses: codecov/codecov-action@v1
        with:
          files: coverage/*.json
